### ISSUE TITLE
Deploy to GitHub releases fails

### ISSUE THREAD

**Issue by lschaefer-sugarcrm** [sugarcrm/school#13]
Error in Travis CI:

`Installing deploy dependencies
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.14.0.gem (100%)
Successfully installed faraday-0.14.0
Fetching: public_suffix-3.0.1.gem (100%)
Successfully installed public_suffix-3.0.1
Fetching: addressable-2.5.2.gem (100%)
Successfully installed addressable-2.5.2
Fetching: sawyer-0.8.1.gem (100%)
Successfully installed sawyer-0.8.1
Fetching: octokit-4.6.2.gem (100%)
Successfully installed octokit-4.6.2
6 gems installed
Fetching: mime-types-2.99.3.gem (100%)
Successfully installed mime-types-2.99.3
1 gem installed
dpl.2
Preparing deploy
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/faraday-0.14.0/lib/faraday/connection.rb:138:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:48:in `user'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:73:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider/releases.rb:77:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:142:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/provider.rb:141:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.47/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy`

**Comment by lschaefer-sugarcrm** [comment]
Fixed with PR #14
